### ISSUE TITLE
Device shows 'connected' but MPS API calls fail after MPS container restarts

### ISSUE THREAD

**Issue by graikhel-intel** [open-amt-cloud-toolkit/mps#1051]
**Describe the bug** 🪲
Device shows 'connected' but API calls fail after MPS container restarts. This happens because we don't clean up the 'connectionstatus' property in database. See line https://github.com/open-amt-cloud-toolkit/mps/blob/main/src/index.ts#L126, this doesn't get executed.

**To Reproduce** 🪜
1. Connect a device to the Toolkit
2. Restart MPS container
3. The device shows connected but in reality NO API calls work

**Screenshots** 🖼️
![image](https://github.com/open-amt-cloud-toolkit/mps/assets/52047020/f9ca9fab-3a23-4222-aae9-885f2c9bdc79)

**AMT Device (please complete the following information):** 🖥️
 - OS: Win 10
 - AMT Version: All supported AMT version
 - AMT Configuration Mode: ACM
 - Network Configuration: DHCP

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: Docker
 - Component & Version: Latest

**Additional context**

**Comment by rsdmike** [comment]
When stopping or restarting docker container, be sure to use `docker stop [containerId]` or `docker restart [containerId]` and this will properly signal MPS to shut down and update the connection status. Using `-f` for force, or `docker kill` without stop , or removing without first stopping triggers  a SIGKILL which signals the process to be killed immediately thus not allowing MPS to properly update the connection status. This is by design at the OS level.
