### ISSUE TITLE
How to secure endpoints of MPS and RCS

### ISSUE THREAD

**Issue by ricardopolo** [open-amt-cloud-toolkit/mps#11]
Hello. I've been testing this repo and it's amazing. Congratulations and thank you for doing this!

I was testing the Active Edge branch and I have a little question:

Will you provide a way to secure the REST API? I've not seen any authentication on it.
Also, I don't see any authentication for the React components.

Any way to secure the endpoints of MPS and RCS?

Thanks!!

**Comment by matt-primrose** [comment]
Hi @ricardopolo 

If you are running in Dev mode, then security is not enforced in MPS and RCS.  This is to help ease development.  If you are running in Production mode (recommended for production deployments) then these interfaces are secured using an API key.  There is also an "auth-enabled" flag that you can turn on in Dev mode to test this security without turning on all of the other security features.  In Production mode, these security features are forced to enabled.

**Comment by ricardopolo** [comment]
Thanks @matt-primrose. Let me ask you an additional question: are there any way to secure the solutions per machine?

I'm seeing that with 1 API key I can access all machines. But are there a way to give a scope to the API Key and only give access to one machine or a group of them?

**Comment by matt-primrose** [comment]
Hi @ricardopolo.  Being a backend service, we are operating under the model that ISVs would manage user or group level access to devices and would manage who has access to what systems based on their role.  In this way we are just another service that the ISV console can access to give remote administration capabilities to the logged in user.  When we issue commands to AMT devices, we do so on behalf of the ISV console, not any specific user.  The ISV console enforces the access controls to the systems.

**Comment by ricardopolo** [comment]
@matt-primrose I can understand that for the REST API. The Key is managed by the ISV Console and provide services transparent for the end user. In this case the authentication is manage and roles is manage by the ISV console. 

However for the React components that are in the front end, there should be API keys in the code provide for the browser, so the end user would know the API Key for access all other systems. Am I understanding right? 
How an ISV could mitigate this in the frontend components without having to give the end user's browser the API key? 

Thanks a lot!

**Comment by matt-primrose** [comment]
Hi @ricardopolo you are correct in the current implementation we have a very simple basic authentication method aligned with using our reference UI.  Our assumption is that an ISV would replace this auth method with their implementation of authentication validation.  As an example, when a user logs into the console an auth token is issued to their browser that can be used for further requests.  When the user starts a KVM session, this auth token is added to the REACT request going to the MPS.  In the webserver.ts file in MPS, the validation of this token is then executed.  Here is a link to this part of the code: https://github.com/open-amt-cloud-toolkit/mps/blob/1b994eabf1be5944a7e955b38486d811efae8c89/src/server/webserver.ts#L131

Since each ISV may have their own method for validating their tokens, we did not specify a specific implementation (Cookies, Session Tokens, OAuth, etc).  On a passing validation of the auth token, request.session.loggedin is set to true and then MPS will allow the connection to be established, otherwise the connection is closed.

**Comment by ricardopolo** [comment]
Thanks @matt-primrose, we will test!
