### ISSUE TITLE
Boot to PXE only works after issuing both boot to PXE and then boot to BIOS

### ISSUE THREAD

**Issue by matt-primrose** [open-amt-cloud-toolkit/mps#752]
**Describe the bug** 🪲
Issuing a power/bootoptions POST call with action 400 (Reboot to PXE), reboots the devices but does not cause the device to boot to the PXE boot options.  However, if you then send a power/bootopions POST call with action 101 (Reboot to BIOS) the device will reboot and go to the PXE boot option.  The device will not boot to BIOS.

**To Reproduce** 🪜
1. Send device power/bootoptions POST call with action set to 400
2. Wait for device to complete reboot
3. Send device power/bootoptions POST call with action set to 101
4. Device will reboot to PXE boot option

**Expected behavior**
Sending power/bootoption POST call with action set to 400 will cause the device to reboot to PXE boot option.  Subsequent reboots (without setting action to 400) will not cause it to boot to PXE boot option.
Sending power/bootoption POST call with action set to 101 after the same call with action set to 400 will cause the device to reboot to BIOS, not PXE boot option

**Screenshots** 🖼️

**AMT Device (please complete the following information):** 🖥️
 - OS: Windows
 - AMT Version: 12.0.85
 - AMT Configuration Mode: Admin Control Mode
 - Network Configuration DHCP

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: Docker
 - Node Version: LTS 16
 - Component & Version: MPS 2.7 (release candidate)

**Additional context**

**Comment by brunomirandades** [comment]
We are currently implementing Boot control in our application, through the toolkit, and noticed the behavior exactly as described in the issue, while testing with version 2.2.
Also, since we noticed version 2.7 stated as a release candidate to receive the fix, even though the issue is yet open, we checked it anyway and it ended up presenting an even worse bug scenario. Both "Power up" and "Reset" commands act on the device as they should, but neither of them lead to PXE nor BIOS screens by using each of their specific commands (400, 401, 100 and 101).

Is there any new estimate for this fix? We would appreciate it if we have an estimate for the next LTS version as well.

**Comment by matt-primrose** [comment]
The linked PR fixes the coding issues we were having when executing boot to PXE calls.  That being said, actually getting a system to boot to PXE is very dependent on the particular BIOS of the system and even the BIOS version.  We had mixed results actually seeing PXE boot in our testing across different test machines.  That being said, all of our calls to AMT to set the boot to PXE option are succeeding and we are able to get several different versions of AMT to reliably boot to PXE.  If there is additional feedback on this issue, please feel free to re-open this issue and provide additional information.
